name: matrix congiguration

on:
  push:
  workflow_dispatch:

jobs: 
  deploy:
      strategy:
      
        
        matrix:
          os: [ubuntu-latest, ubuntu-20.4, windows-latest]
          Images: [hello-world, alpine]
          exclude:
            - images: alpine
            - os: windows-latest
          include:
            - images: amd64/alpine
            - os: ubuntu-20.4
    
      runs-on: ${{matrix.os}}
      steps:
      - name: Echo Docker Details
        run: docker info
      - name: Run Images
        run: docker run ${{matrix.Images}} 



    
    # deploy-on-windows:
    #   runs-on: windows-latest
    #   steps:
    #    - name: Echo Docker Details
    #      run: docker info
    #    - name: Run Images
    #      run: docker run hello-world
          

