name: Exploring Variables and Secrets

on: 
    workflow_dispatch: 
    # schedule:
    #     - cron: "*/1 * * * *"
      
# push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
 docker:
  runs-on: ubuntu-latest
  steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

      - name: Docker Login
        
         
        run: echo docker login --username=${{vars.DOCKER_USERNAME}} --password=${{secrets.DOCKER_PASSWORD}}

      - name: Docker Publish
        
        run: echo docker build -t $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest


 deploy:
        
    needs: docker
    concurrency: 
      group: production deployment
      cancel-in-progress: false
      
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: |
        echo docker build -t $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest
        sleep 6000s

    # docker:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Build
    #       run: docker build -t docker.io/dockerUsernmae/imageName:latest

    #     - name: Docker Login
    #       run: docker login --username=dockerUsername --password=s3UrePaSsword

    #     - name: Docker Publish
    #       run: docker push docker.io/dockerUsername/imageName:latest

    # deploy:
    #   needs: docker
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Docker Run
    #     run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest

##################### enviornemnt variable at STEP level ######################

    # docker:
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Docker Build
    #     env:
    #       CONTAINER_REGISTRY: docker.io
    #       DCOKER_USERNAME: siddharth1
    #       IMAGE_NAME: github-actions-nginx
    #     run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    #   - name: Docker Login
    #     env:
    #       DOCKER_PASSWORD: s3cUrePaSsw0rd
    #       DOCKER_USERNAME: siddharthi
    #     run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    #   - name: Docker Publish
    #     env: 
    #       CONTAINER_REGISTRY: docker.io
    #       DCOKER_USERNAME: siddharth1
    #       IMAGE_NAME: github-actions-nginx
    #     run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


    # deploy:
    #   needs: docker
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Docker run
    #     env: 
    #       CONTAINER_REGISTRY: docker.io
    #       DCOKER_USERNAME: siddharth1
    #       IMAGE_NAME: github-actions-nginx
    #     run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


##################### enviornemnt variable at job level ######################

# docker:
#   env:
#         CONTAINER_REGISTRY: docker.io
#         DCOKER_USERNAME: siddharth1
#         IMAGE_NAME: github-actions-nginx
#   runs-on: ubuntu-latest
#   steps:
#       - name: Docker Build
#         run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#       - name: Docker Login
#         env:
#           DOCKER_PASSWORD: s3cUrePaSsw0rd
#           DOCKER_USERNAME: siddharthi
#         run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#       - name: Docker Publish
#         env: 
#         run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


#     deploy:
#         env: 
#           CONTAINER_REGISTRY: docker.io
#           DCOKER_USERNAME: siddharth1
#           IMAGE_NAME: github-actions-nginx
#         needs: docker
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker run
        
#         run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


##################### enviornemnt variable at workflow level ######################

# jobs:
#  docker:
#   runs-on: ubuntu-latest
#   steps:
#       - name: Docker Build
#         run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

#       - name: Docker Login
#         env:
#           DOCKER_PASSWORD: s3cUrePaSsw0rd
#           DOCKER_USERNAME: siddharthi
#         run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

#       - name: Docker Publish
        
#         run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


#  deploy:
        
#     needs: docker
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker run
#       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      ##################### enviornemnt variable using repo secrets  ######################


